name: Build mod_sat_runner

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout SkedAIServer repository
        uses: actions/checkout@v4
        with:
          path: 'SkedAIServer'
      
      - name: Clone ORTools repository
        run: git clone -b main https://github.com/google/or-tools or-tools
        
      - name: Copy mod_sat_runner.cc to OR-Tools
        run: Copy-Item SkedAIServer\mod_sat_runner\mod_sat_runner.cc or-tools\examples\cpp
        
      - name: Install make
        run: choco install make

      - name: Setup MSVC environment for Visual Studio 2022
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.3

      - name: Build mod_sat_runner
        run: |
          cd or-tools
          make build SOURCE=examples/cpp/mod_sat_runner.cc

      - name: Upload compiled binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod_sat_runner-binary
          path: or-tools/temp_cpp/mod_sat_runner/build/bin/mod_sat_runner.exe
