name: test_v1

on: [push]

jobs:
  native:
    strategy:
      matrix:
        cmake: [
          {generator: "Visual Studio 17 2022", config: Release, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
        ]
      fail-fast: false
    name: Windows • ${{ matrix.cmake.generator }} • C++
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install make
        run: |
          choco install make
      - name: Check make
        run: |
          make --version
          make -G || true
