name: Complete Windows Build Workflow

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2



      - name: Check for changes in mod_sat_runner.cc
        run: |
          $changed = git diff HEAD~1 --name-only | Select-String -Pattern "mod_sat_runner/mod_sat_runner.cc"
          if ($null -ne $changed) {
            echo "MOD_SAT_RUNNER_CHANGED=true" >> $env:GITHUB_ENV
          } else {
            echo "MOD_SAT_RUNNER_CHANGED=false" >> $env:GITHUB_ENV
          }
        shell: powershell

      - name: Cache OR-Tools Build
        if: env.MOD_SAT_RUNNER_CHANGED == 'true'
        uses: actions/cache@v4
        with:
          path: SkedAIServer/or-tools
          key: or-tools-${{ runner.os }}-${{ hashFiles('SkedAIServer/mod_sat_runner/mod_sat_runner.cc', '**/CMakeLists.txt', '**/*.h') }}
          restore-keys: |
            or-tools-${{ runner.os }}-

      - name: Clone ORTools repository
        if: env.MOD_SAT_RUNNER_CHANGED == 'true' && steps.cache-or-tools.outputs.cache-hit != 'true'
        run: git clone -b main https://github.com/google/or-tools SkedAIServer/or-tools
        
      - name: Copy mod_sat_runner.cc to OR-Tools
        if: env.MOD_SAT_RUNNER_CHANGED == 'true'
        run: Copy-Item SkedAIServer\mod_sat_runner\mod_sat_runner.cc SkedAIServer/or-tools/examples/cpp

      - name: Ensure Make is installed
        if: env.MOD_SAT_RUNNER_CHANGED == 'true'
        run: |
          choco list --local-only | Select-String "make" || choco install make

      - name: Setup MSVC environment for Visual Studio 2022
        if: env.MOD_SAT_RUNNER_CHANGED == 'true'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.3

      - name: Build mod_sat_runner
        if: env.MOD_SAT_RUNNER_CHANGED == 'true'
        run: |
          cd SkedAIServer/or-tools
          make build SOURCE=examples/cpp/mod_sat_runner.cc

      - name: Upload compiled mod_sat_runner as artifact
        if: env.MOD_SAT_RUNNER_CHANGED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: mod_sat_runner
          path: SkedAIServer/or-tools/temp_cpp/mod_sat_runner/build/Release/bin/mod_sat_runner.exe



      - name: Check for changes in authenticator.js
        run: |
          $changed = git diff HEAD~1 --name-only | Select-String -Pattern "authenticator/authenticator.js"
          if ($null -ne $changed) {
            echo "AUTHENTICATOR_CHANGED=true" >> $env:GITHUB_ENV
          } else {
            echo "AUTHENTICATOR_CHANGED=false" >> $env:GITHUB_ENV
          }
        shell: powershell

      - name: setup Node.js environment for packages
        if: env.AUTHENTICATOR_CHANGED == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install dependencies for authenticator.js
        if: env.AUTHENTICATOR_CHANGED == 'true'
        run: |
          cd authenticator
          npm install
        shell: powershell

      - name: Build authenticator.exe
        if: env.AUTHENTICATOR_CHANGED == 'true'
        run: |
          cd authenticator
          npm run dist
        shell: powershell

      - name: Upload compiled SkedAuthenticator.exe as artifact
        if: env.USER_SERVER_MAIN_CHANGED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: SkedAuthenticator
          path: authenticator/build/win-unpacked/SkedAuthenticator.exe



      - name: Check for changes in userServerMain.js
        run: |
          $changed = git diff HEAD~1 --name-only | Select-String -Pattern "userServerMain/userServerMain.js"
          if ($null -ne $changed) {
            echo "USER_SERVER_MAIN_CHANGED=true" >> $env:GITHUB_ENV
          } else {
            echo "USER_SERVER_MAIN_CHANGED=false" >> $env:GITHUB_ENV
          }
        shell: powershell

      - name: setup Node.js environment for packages
        if: env.USER_SERVER_MAIN_CHANGED == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install dependencies for userServerMain.js
        if: env.USER_SERVER_MAIN_CHANGED == 'true'
        run: |
          cd userServerMain
          npm install -g nexe
          npm install
        shell: powershell

      - name: setup Node.js environment for nexe
        uses: actions/setup-node@v4
        with:
          node-version: '14.15.3'

      - name: Build userServerMain.js to main.exe
        if: env.USER_SERVER_MAIN_CHANGED == 'true'
        run: |
          cd userServerMain
          nexe userServerMain.js -o main.exe
        shell: powershell

      - name: Upload compiled main.exe as artifact
        if: env.USER_SERVER_MAIN_CHANGED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: userServerMain/main.exe



      - name: Check for changes in Inno Setup script
        run: |
          $changed = git diff HEAD~1 --name-only | Select-String -Pattern "SkedAIUserServerInstallerSilent.iss"
          if ($null -ne $changed) {
            echo "INNO_SETUP_SCRIPT_CHANGED=true" >> $env:GITHUB_ENV
          } else {
            echo "INNO_SETUP_SCRIPT_CHANGED=false" >> $env:GITHUB_ENV
          }
        shell: powershell

      - name: Determine if need to build installer
        run: |
          if ($env:MOD_SAT_RUNNER_CHANGED -eq "true" -or
              $env:AUTHENTICATOR_CHANGED -eq "true" -or
              $env:USER_SERVER_MAIN_CHANGED -eq "true" -or
              $env:INNO_SETUP_SCRIPT_CHANGED -eq "true") {
            echo "INNO_SETUP_CHANGED=true" >> $env:GITHUB_ENV
          } else {
            echo "INNO_SETUP_CHANGED=false" >> $env:GITHUB_ENV
          }
        shell: powershell

      - name: Install Inno Setup
        if: env.INNO_SETUP_CHANGED == 'true'
        run: |
          choco install innosetup

      - name: Compile Installer
        if: env.INNO_SETUP_CHANGED == 'true'
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" SkedAIUserServerInstallerSilent.iss
        shell: cmd
        
      - name: Upload Installer as Artifact
        if: env.INNO_SETUP_CHANGED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Output\SkedAIUserServerInstaller.exe
